In [8]:
from odf.sbe import read_hex
import odf.sbe.accessors
import numpy as np

In [9]:
%%time
ds = read_hex("00102.hex")

CPU times: user 183 ms, sys: 15.9 ms, total: 199 ms
Wall time: 214 ms


In [11]:
# The accessor lets you get frequencies like they are an attribtue on sbe
ds.sbe.f0

<xarray.DataArray 'hex' (scan: 78491)> Size: 628kB
array([3367.0234375 , 3366.953125  , 3366.859375  , ..., 2919.74609375,
       2919.74609375, 2919.75390625])
Dimensions without coordinates: scan

In [12]:
# just change the channel number
ds.sbe.f3

<xarray.DataArray 'hex' (scan: 78491)> Size: 628kB
array([3785.48046875, 3785.53125   , 3785.61328125, ..., 3400.44140625,
       3400.44140625, 3400.46484375])
Dimensions without coordinates: scan

In [13]:
# There are no guard rails right now
ds.sbe.f10

<xarray.DataArray 'hex' (scan: 78491)> Size: 628kB
array([12260.75      , 12260.75      , 12260.75      , ...,
       12260.74609375, 12260.74609375, 12260.74609375])
Dimensions without coordinates: scan

In [14]:
# volts work the same way
ds.sbe.v0

<xarray.DataArray 'hex' (scan: 78491)> Size: 628kB
array([0.02564103, 0.02564103, 0.02564103, ..., 0.03663004, 0.03663004,
       0.03663004])
Dimensions without coordinates: scan

In [16]:
ds.sbe.v7

<xarray.DataArray 'hex' (scan: 78491)> Size: 628kB
array([2.69108669, 2.69108669, 2.69108669, ..., 2.65079365, 2.65079365,
       2.65079365])
Dimensions without coordinates: scan